const I18N={ja:{voices:'ボイス',library:'ライブラリ',runtime:'ランタイム',setup:'音声基本環境をセットアップ',generate:'生成',transcribe:'文字起こし',description:'説明',text:'テキスト',language:'言語',recommended:'推奨',optional:'任意パック'},en:{voices:'Voices',library:'Library',runtime:'Runtime',setup:'Set up Speech Essentials',generate:'Generate',transcribe:'Transcribe',description:'Description',text:'Text',language:'Language',recommended:'Recommended',optional:'Optional packs'}};
let locale=(navigator.language||'ja').startsWith('en')?'en':'ja',task='speech',level='easy',socket=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], t=k=>I18N[locale][k]||k;
function applyLocale(){document.documentElement.lang=locale;$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));renderTask();loadSetup();}
$('#localeBtn').onclick=()=>{locale=locale==='ja'?'en':'ja';applyLocale()};
$$('#topnav button').forEach(b=>b.onclick=()=>{$$('#topnav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active'); if(b.dataset.view==='library')loadAssets(); if(b.dataset.view==='voices')loadVoices();});
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');task=b.dataset.task;renderTask()});
$$('.level').forEach(b=>b.onclick=()=>{$$('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');level=b.dataset.level;renderTask()});
function commonAdvanced(){return level==='easy'?'':`<details open><summary>${level==='expert'?'Expert':'Customize'}</summary><div class="field"><label>Quality</label><select id="quality"><option value="balanced">${t('recommended')}</option><option value="fast">Fast</option><option value="quality">High quality</option></select></div>${level==='expert'?'<div class="field"><label>Engine pin</label><input id="engine" placeholder="auto"></div>':''}</details>`}
function renderTask(){let html='';if(task==='speech')html=`<div class="card"><div class="field"><label>${t('text')}</label><textarea id="text" placeholder="こんにちは / Hello"></textarea></div><div class="field"><label>${t('language')}</label><select id="lang"><option value="auto">Auto</option><option value="ja">日本語</option><option value="en">English</option></select></div>${commonAdvanced()}<div class="row"><button class="primary" onclick="runTask('speech.tts.synthesize')">${t('generate')}</button></div></div>`;else if(task==='transcribe')html=`<div class="card"><p class="muted">Host grant integration uses scoped grant IDs. Standalone testing can use Expert staged input.</p><div class="field"><label>${t('language')}</label><select id="lang"><option value="auto">Auto</option><option value="ja">日本語</option><option value="en">English</option></select></div>${commonAdvanced()}<button class="primary" onclick="runTask('speech.asr.transcribe')">${t('transcribe')}</button></div>`;else if(task==='sfx'||task==='music')html=`<div class="card"><div class="field"><label>${t('description')}</label><textarea id="text"></textarea></div>${commonAdvanced()}<button class="primary" onclick="runTask('${task==='sfx'?'audio.sfx.generate':'music.generate'}')">${t('generate')}</button></div>`;else html=`<div class="card"><h3>Localization Studio</h3><p class="muted">JP / EN paired dialogue batches, stable line IDs, voice mapping and QA state are stored server-side.</p><button onclick="createDemoBatch()">Create demo JP/EN batch</button></div>`;$('#taskPanel').innerHTML=html;}
async function runTask(kind){const text=$('#text')?.value||'';const lang=$('#lang')?.value||'auto';const quality=$('#quality')?.value||'balanced';const engine=$('#engine')?.value||null;const body={task:kind,input:kind==='speech.tts.synthesize'?{text}:{prompt:text},profile:'default',quality,content_language:lang,output:{format:'wav',sample_rate:null,channels:null},routing:{engine,model:null,device:'auto'},seed:null,project_output_grant:null};const r=await fetch('/addon/v1/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();showJob(d.job_id)}
async function showJob(id){const r=await fetch('/addon/v1/jobs/'+encodeURIComponent(id));const j=await r.json();$('#activeJob').innerHTML=`<div class="card"><b>${j.task}</b> — ${j.state}<div class="progress"><i style="width:${Math.round(j.progress*100)}%"></i></div><p class="muted">${j.error_message||j.result?.message||''}</p>${['queued','running'].includes(j.state)?`<button onclick="cancelJob('${id}')">Cancel</button>`:''}</div>`;if(['queued','running'].includes(j.state))setTimeout(()=>showJob(id),1000);else loadAssets()}
async function cancelJob(id){await fetch('/addon/v1/jobs/'+encodeURIComponent(id),{method:'DELETE'});showJob(id)}
async function loadAssets(){const d=await (await fetch('/addon/v1/assets')).json();$('#assetList').innerHTML=d.assets.map(a=>`<div class="asset"><b>${a.id}</b> · ${a.duration_ms||'-'} ms<br><audio controls src="/addon/v1/assets/${encodeURIComponent(a.id)}/content"></audio></div>`).join('')||'<p class="muted">No assets</p>'}
async function loadVoices(){const d=await (await fetch('/addon/v1/voices')).json();$('#voiceList').innerHTML=d.voices.map(v=>`<div class="voice"><b>${v.name}</b> · ${v.languages.join('/')}</div>`).join('')||'<p class="muted">No saved voices</p>'}
async function loadSetup(){const d=await (await fetch('/addon/v1/setup/status')).json();$('#serviceState').textContent=d.state;$('#setupPanel').innerHTML=`<div class="card"><h3>Speech Essentials</h3><p>${d.state}</p>${d.state!=='available'?`<button class="primary" onclick="applySetup('speech-essentials')">${t('setup')}</button>`:''}</div><div class="card"><h3>${t('optional')}</h3><div class="row"><button onclick="applySetup('game-audio')">Game Audio</button><button onclick="applySetup('music')">Music</button></div></div>`}
async function applySetup(profile){const r=await fetch('/addon/v1/setup/apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profile,components:[],accepted_terms:[]})});const d=await r.json();$('#setupPanel').insertAdjacentHTML('afterbegin',`<div class="card">${d.setup_id}: running</div>`)}
async function createDemoBatch(){const body={name:'Demo',profile:{filename:'{line_id}_{locale}.wav'},lines:[{line_id:'hello',character:'A',ja_text:'こんにちは',en_text:'Hello',voice_id:null}]};const d=await (await fetch('/addon/v1/localization/batches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})).json();alert(d.id)}
function connect(){if(socket&&socket.readyState===WebSocket.OPEN)return;const proto=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${proto}://${location.host}/addon/v1/events`);socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='job')showJob(d.job_id);if(d.type==='setup')loadSetup()};socket.onclose=()=>{socket=null};}
document.addEventListener('visibilitychange',()=>{if(!document.hidden){connect();loadSetup();}});window.addEventListener('pageshow',()=>{connect();loadSetup()});renderTask();applyLocale();connect();loadAssets();loadVoices();
