const I18N={
  ja:{voices:'ボイス',library:'ライブラリ',runtime:'ランタイム',setup:'音声基本環境をセットアップ',generate:'生成',transcribe:'文字起こし',description:'説明',text:'テキスト',language:'言語',recommended:'おすすめ',optional:'任意パック',selectAudio:'音声ファイルを選択',noAudio:'音声ファイルを選択してください',bridgeOnly:'ControlDeckから開いて選択してください',clone:'参照音声から作成',design:'声をデザイン',builtIn:'組み込みボイス',save:'保存',name:'名前',rights:'この音声を利用・複製する権利があることを確認します',terms:'Stability AI Community Licenseを確認・同意しました',install:'セットアップ',musicExperimental:'MusicのROCm経路は実機検証前のexperimentalです',setupRequired:'この機能の追加セットアップが必要です'},
  en:{voices:'Voices',library:'Library',runtime:'Runtime',setup:'Set up Speech Essentials',generate:'Generate',transcribe:'Transcribe',description:'Description',text:'Text',language:'Language',recommended:'Recommended',optional:'Optional packs',selectAudio:'Choose audio file',noAudio:'Choose an audio file first',bridgeOnly:'Open from ControlDeck to choose a file',clone:'Create from reference audio',design:'Design a voice',builtIn:'Built-in voice',save:'Save',name:'Name',rights:'I confirm that I have the rights/permission to use and clone this voice',terms:'I reviewed and accept the Stability AI Community License',install:'Set up',musicExperimental:'The Music ROCm route is experimental until target-hardware validation.',setupRequired:'This capability needs an optional setup pack'}
};

const state={locale:(navigator.language||'ja').startsWith('en')?'en':'ja',task:'speech',level:'easy',socket:null,reconnectTimer:0,reconnectAttempt:0,bridgePort:null,nonce:'',activeJob:'',audioGrant:'',audioName:'',voiceReferenceGrant:'',voiceReferenceName:'',voices:[],capabilities:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], t=k=>I18N[state.locale][k]||k;
const frameRoot=location.pathname.startsWith('/addon-frame/')?location.pathname.split('/').slice(0,3).join('').replace(/^$/,''):'';
// split/join above is intentionally not used for routing: preserve slashes explicitly.
const proxyRoot=location.pathname.startsWith('/addon-frame/')?'/'+location.pathname.split('/').filter(Boolean).slice(0,2).join('/'):'';
const API=`${proxyRoot}/addon/v1`;
const apiUrl=path=>`${API}${path}`;

function applyTheme(theme={}){const root=document.documentElement;for(const key of ['bg','surface','text','border','muted','accent'])if(typeof theme[key]==='string')root.style.setProperty(`--${key}`,theme[key]);if(theme.color_scheme)root.style.colorScheme=theme.color_scheme;if(theme.locale==='ja'||theme.locale==='en'){state.locale=theme.locale;applyLocale();}}
function callHost(method,params={}){if(!state.bridgePort)return Promise.reject({code:'bridge_unavailable'});return new Promise((resolve,reject)=>{const id=`sonic-forge-host-${Date.now()}-${Math.random().toString(36).slice(2)}`;const listener=e=>{const m=e.data;if(m?.type!=='response'||m.id!==id)return;state.bridgePort.removeEventListener('message',listener);m.ok?resolve(m.result):reject(m.error)};state.bridgePort.addEventListener('message',listener);state.bridgePort.postMessage({id,method,params,session_nonce:state.nonce})})}
window.addEventListener('message',event=>{let expected=location.origin;try{if(document.referrer)expected=new URL(document.referrer).origin}catch{}if(event.source!==parent||event.origin!==expected||event.data?.type!=='control-deck-host.connected'||!event.ports[0])return;state.bridgePort=event.ports[0];state.nonce=event.data.session_nonce;applyTheme(event.data.theme||{});state.bridgePort.onmessage=e=>{const m=e.data;if(m?.type!=='event')return;if(m.event==='locale.changed'&&(m.data?.locale==='ja'||m.data?.locale==='en')){state.locale=m.data.locale;applyLocale()}if(m.event==='theme.changed')applyTheme(m.data||{});if(m.event==='visibility.changed'&&m.data?.visible){connect();reloadAuthoritative()}};state.bridgePort.start?.()});
if(parent!==window)parent.postMessage({type:'control-deck-addon.connect',bridge_version:'1.0'},'*');

async function api(path,options={}){const response=await fetch(apiUrl(path),options);const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={detail:text}}if(!response.ok)throw data.detail||data.error||{message:`HTTP ${response.status}`};return data}
function errorText(error){return typeof error==='string'?error:(error?.message||error?.code||JSON.stringify(error||{}))}

function applyLocale(){document.documentElement.lang=state.locale;$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));renderTask();loadSetup();renderVoices()}
$('#localeBtn').onclick=()=>{state.locale=state.locale==='ja'?'en':'ja';applyLocale()};
$$('#topnav button').forEach(b=>b.onclick=()=>{$$('#topnav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='library')loadAssets();if(b.dataset.view==='voices')loadVoices();if(b.dataset.view==='runtime')loadSetup()});
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.task=b.dataset.task;renderTask()});
$$('.level').forEach(b=>b.onclick=()=>{$$('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.level=b.dataset.level;renderTask()});

function commonAdvanced(){return state.level==='easy'?'':`<details open><summary>${state.level==='expert'?'Expert':'Customize'}</summary><div class="field"><label>Quality</label><select id="quality"><option value="balanced">${t('recommended')}</option><option value="fast">Fast</option><option value="quality">High quality</option></select></div>${state.level==='expert'?'<div class="field"><label>Engine pin</label><input id="engine" placeholder="auto"></div><div class="field"><label>Model pin</label><input id="model" placeholder="auto"></div>':''}</details>`}
function capability(id){return state.capabilities?.capabilities?.find(x=>x.id===id)||null}
function setupGate(capabilityId,profile){const cap=capability(capabilityId);if(!cap||cap.state==='available')return'';return `<div class="card"><b>${t('setupRequired')}</b><p class="muted">${cap.reason||cap.reason_code||''}</p><button onclick="openRuntime('${profile}')">${t('install')}</button></div>`}
function voiceOptions(){return `<option value="">${t('builtIn')}</option>`+state.voices.map(v=>`<option value="${escapeHtml(v.id)}">${escapeHtml(v.name)} · ${(v.languages||[]).join('/')}</option>`).join('')}
function renderTask(){let html='';if(state.task==='speech')html=`${setupGate('speech.tts.synthesize','speech-essentials')}<div class="card"><div class="field"><label>${t('text')}</label><textarea id="text" placeholder="こんにちは / Hello"></textarea></div><div class="field"><label>Voice</label><select id="voice">${voiceOptions()}</select></div><div class="field"><label>${t('language')}</label><select id="lang"><option value="auto">Auto</option><option value="ja">日本語</option><option value="en">English</option></select></div>${commonAdvanced()}<div class="row"><button class="primary" onclick="runTask('speech.tts.synthesize')">${t('generate')}</button></div></div>`;else if(state.task==='transcribe')html=`${setupGate('speech.asr.transcribe','speech-essentials')}<div class="card"><div class="field"><label>Audio</label><div class="row"><button onclick="pickAudio()">${t('selectAudio')}</button><span class="muted" id="audioName">${escapeHtml(state.audioName||'')}</span></div></div><div class="field"><label>${t('language')}</label><select id="lang"><option value="auto">Auto</option><option value="ja">日本語</option><option value="en">English</option></select></div>${commonAdvanced()}<button class="primary" onclick="runTask('speech.asr.transcribe')">${t('transcribe')}</button></div>`;else if(state.task==='sfx')html=`${setupGate('audio.sfx.generate','game-audio')}<div class="card"><div class="field"><label>${t('description')}</label><textarea id="text"></textarea></div><div class="field"><label>Length</label><input id="duration" type="number" value="3" min="0.1" max="120" step="0.1"></div>${commonAdvanced()}<button class="primary" onclick="runTask('audio.sfx.generate')">${t('generate')}</button></div>`;else if(state.task==='music')html=`${setupGate('music.generate','music')}<div class="card"><p class="muted">${t('musicExperimental')}</p><div class="field"><label>${t('description')}</label><textarea id="text"></textarea></div><div class="row"><label>BPM <input id="bpm" type="number" min="30" max="300"></label><label>Length <input id="duration" type="number" value="30" min="10" max="600"></label></div>${commonAdvanced()}<button class="primary" onclick="runTask('music.generate')">${t('generate')}</button></div>`;else html=`<div class="card"><h3>Localization Studio</h3><p class="muted">line_id | character | Japanese | English — one row per line.</p><textarea id="locRows" rows="10" placeholder="hello|A|こんにちは|Hello\nbye|A|またね|See you"></textarea><div class="field"><label>Batch name</label><input id="locName" value="Dialogue"></div><button class="primary" onclick="createBatchFromRows()">Create batch</button><div id="locResult"></div></div>`;$('#taskPanel').innerHTML=html}

async function pickAudio(){try{const grant=await callHost('host.file.pick',{mode:'file',title:t('selectAudio')});if(!grant?.grant_id)return;state.audioGrant=grant.grant_id;state.audioName=grant.name||'audio';renderTask()}catch(error){alert(error?.code==='bridge_unavailable'?t('bridgeOnly'):errorText(error))}}
async function runTask(kind){try{const text=$('#text')?.value||'';const lang=$('#lang')?.value||'auto';const quality=$('#quality')?.value||'balanced';const engine=$('#engine')?.value||null;const model=$('#model')?.value||null;let input={};if(kind==='speech.tts.synthesize')input={text,voice_id:$('#voice')?.value||undefined};else if(kind==='speech.asr.transcribe'){if(!state.audioGrant){alert(t('noAudio'));return}input={audio_grant:state.audioGrant};}else if(kind==='music.generate')input={prompt:text,duration_sec:Number($('#duration')?.value||30),bpm:$('#bpm')?.value?Number($('#bpm').value):null,instrumental:true};else input={prompt:text,duration_sec:Number($('#duration')?.value||3)};const d=await api('/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task:kind,input,profile:'default',quality,content_language:lang,output:{format:'wav',sample_rate:null,channels:null},routing:{engine,model,device:'auto'},seed:null,project_output_grant:null})});state.activeJob=d.job_id;await showJob(d.job_id)}catch(error){alert(errorText(error))}}
async function showJob(id){try{const j=await api('/jobs/'+encodeURIComponent(id));if(state.activeJob!==id&&['queued','running'].includes(j.state))state.activeJob=id;$('#activeJob').innerHTML=`<div class="card"><b>${escapeHtml(j.task)}</b> — ${escapeHtml(j.state)}<div class="progress"><i style="width:${Math.round((j.progress||0)*100)}%"></i></div><p class="muted">${escapeHtml(j.error_message||j.result?.message||j.result?.text||'')}</p>${['queued','running'].includes(j.state)?`<button onclick="cancelJob('${escapeHtml(id)}')">Cancel</button>`:''}${j.result?.asset_id?`<p><audio controls src="${apiUrl('/assets/'+encodeURIComponent(j.result.asset_id)+'/content')}"></audio></p>`:''}</div>`;if(['queued','running'].includes(j.state)&&!socketOpen())setTimeout(()=>showJob(id),2000);else if(!['queued','running'].includes(j.state))loadAssets()}catch(error){if(!socketOpen())setTimeout(()=>showJob(id),3000)}}
async function cancelJob(id){try{await api('/jobs/'+encodeURIComponent(id),{method:'DELETE'});showJob(id)}catch(error){alert(errorText(error))}}
async function loadActiveJobs(){try{const d=await api('/jobs?limit=30');const active=(d.jobs||[]).find(j=>['queued','running'].includes(j.state));if(active){state.activeJob=active.id;showJob(active.id)}}catch{}}
async function loadAssets(){try{const d=await api('/assets');$('#assetList').innerHTML=(d.assets||[]).map(a=>`<div class="asset"><b>${escapeHtml(a.id)}</b> · ${a.duration_ms||'-'} ms<br><audio controls src="${apiUrl('/assets/'+encodeURIComponent(a.id)+'/content')}"></audio></div>`).join('')||'<p class="muted">No assets</p>'}catch(error){$('#assetList').textContent=errorText(error)}}

async function loadVoices(){try{const d=await api('/voices');state.voices=d.voices||[];renderVoices();if(state.task==='speech')renderTask()}catch(error){$('#voiceList').textContent=errorText(error)}}
function renderVoices(){const list=state.voices.map(v=>`<div class="voice"><b>${escapeHtml(v.name)}</b> · ${(v.languages||[]).join('/')} · ${escapeHtml(v.source_type)} <button onclick="deleteVoice('${escapeHtml(v.id)}')">Delete</button></div>`).join('');$('#voiceList').innerHTML=`<div class="card"><h3>Voice profile</h3><div class="field"><label>${t('name')}</label><input id="voiceName"></div><div class="field"><label>Type</label><select id="voiceType" onchange="renderVoiceFields()"><option value="built-in">${t('builtIn')}</option><option value="design">${t('design')}</option><option value="clone">${t('clone')}</option></select></div><div id="voiceFields"></div><button class="primary" onclick="saveVoice()">${t('save')}</button></div>${list||'<p class="muted">No saved voices</p>'}`;renderVoiceFields()}
function renderVoiceFields(){const type=$('#voiceType')?.value||'built-in';if(!$('#voiceFields'))return;if(type==='built-in')$('#voiceFields').innerHTML='<div class="field"><label>Qwen speaker</label><input id="voiceSpeaker" value="Ryan"></div>';else if(type==='design')$('#voiceFields').innerHTML='<div class="field"><label>Voice design instruction</label><textarea id="voiceInstruction"></textarea></div>';else $('#voiceFields').innerHTML=`<div class="row"><button onclick="pickVoiceReference()">${t('selectAudio')}</button><span class="muted">${escapeHtml(state.voiceReferenceName)}</span></div><div class="field"><label>Reference transcript</label><textarea id="voiceRefText"></textarea></div><label><input id="voiceRights" type="checkbox"> ${t('rights')}</label>`}
async function pickVoiceReference(){try{const g=await callHost('host.file.pick',{mode:'file',title:t('selectAudio')});if(g?.grant_id){state.voiceReferenceGrant=g.grant_id;state.voiceReferenceName=g.name||'reference';renderVoiceFields()}}catch(error){alert(error?.code==='bridge_unavailable'?t('bridgeOnly'):errorText(error))}}
async function saveVoice(){try{const type=$('#voiceType').value;const recipe={};let rights=false;if(type==='built-in')recipe.speaker=$('#voiceSpeaker')?.value||'Ryan';if(type==='design')recipe.design_instruction=$('#voiceInstruction')?.value||'';if(type==='clone'){if(!state.voiceReferenceGrant){alert(t('noAudio'));return}recipe.reference_grant=state.voiceReferenceGrant;recipe.reference_text=$('#voiceRefText')?.value||'';rights=$('#voiceRights')?.checked===true;if(!rights){alert(t('rights'));return}}await api('/voices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('#voiceName').value,source_type:type,languages:['ja','en'],engine_id:'tts.qwen3',recipe,rights_confirmed:rights})});state.voiceReferenceGrant='';state.voiceReferenceName='';loadVoices()}catch(error){alert(errorText(error))}}
async function deleteVoice(id){try{await api('/voices/'+encodeURIComponent(id),{method:'DELETE'});loadVoices()}catch(error){alert(errorText(error))}}

async function loadCapabilities(){try{state.capabilities=await api('/capabilities');renderTask()}catch{}}
async function loadSetup(){try{const d=await api('/setup/status');$('#serviceState').textContent=d.state;const game=d.components.find(x=>x.id==='game-audio');const music=d.components.find(x=>x.id==='music');const speech=d.components.find(x=>x.id==='speech-essentials');let musicPlan={blockers:[]};try{musicPlan=await api('/setup/plan?profile=music')}catch{}$('#setupPanel').innerHTML=`<div class="card"><h3>Speech Essentials</h3><p>${escapeHtml(speech?.state||'missing')}</p>${speech?.state!=='available'?`<button class="primary" onclick="applySetup('speech-essentials')">${t('setup')}</button>`:''}</div><div class="card"><h3>Game Audio · Stable Audio 3 Small-SFX</h3><p>${escapeHtml(game?.state||'missing')}</p><label><input id="stabilityTerms" type="checkbox"> ${t('terms')}</label><p><button onclick="applySetup('game-audio')">${t('install')}</button></p></div><div class="card"><h3>Music · ACE-Step 1.5</h3><p>${escapeHtml(music?.state||'missing')}</p><p class="muted">${t('musicExperimental')} ${(musicPlan.blockers||[]).map(escapeHtml).join(' · ')}</p><button ${musicPlan.blockers?.length?'disabled':''} onclick="applySetup('music')">${t('install')}</button></div>`}catch(error){$('#setupPanel').textContent=errorText(error)}}
async function applySetup(profile){const accepted=[];if(profile==='game-audio'){if(!$('#stabilityTerms')?.checked){alert(t('terms'));return}accepted.push('stability-ai-community-license')}try{const d=await api('/setup/apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profile,components:[],accepted_terms:accepted})});state.activeJob=d.job_id;showJob(d.job_id)}catch(error){alert(errorText(error))}}
function openRuntime(profile){$('#topnav button[data-view="runtime"]').click();loadSetup()}

async function createBatchFromRows(){try{const rows=($('#locRows')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [line_id,character,ja_text,en_text]=line.split('|');return{line_id,character:character||null,ja_text:ja_text||null,en_text:en_text||null,voice_id:null}});const d=await api('/localization/batches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('#locName')?.value||'Dialogue',profile:{filename:'{line_id}_{locale}.wav'},lines:rows})});$('#locResult').textContent=`${d.id}: ${d.lines} lines`}catch(error){alert(errorText(error))}}

function socketOpen(){return state.socket&&state.socket.readyState===WebSocket.OPEN}
function scheduleReconnect(){clearTimeout(state.reconnectTimer);if(document.hidden)return;const delay=Math.min(30000,1000*(2**Math.min(state.reconnectAttempt++,5)));state.reconnectTimer=setTimeout(connect,delay)}
function connect(){if(state.socket&&(state.socket.readyState===WebSocket.OPEN||state.socket.readyState===WebSocket.CONNECTING))return;clearTimeout(state.reconnectTimer);const proto=location.protocol==='https:'?'wss':'ws';state.socket=new WebSocket(`${proto}://${location.host}${API}/events`);state.socket.onopen=()=>{state.reconnectAttempt=0;reloadAuthoritative()};state.socket.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch{return}if(d.type==='job'&&d.job_id){if(!state.activeJob||state.activeJob===d.job_id){state.activeJob=d.job_id;showJob(d.job_id)}}if(d.type==='setup'){loadSetup();loadCapabilities()}};state.socket.onerror=()=>{};state.socket.onclose=()=>{state.socket=null;scheduleReconnect()}}
async function reloadAuthoritative(){await Promise.allSettled([loadSetup(),loadCapabilities(),loadAssets(),loadVoices(),loadActiveJobs()])}
document.addEventListener('visibilitychange',()=>{if(!document.hidden){connect();reloadAuthoritative()}});window.addEventListener('pageshow',()=>{connect();reloadAuthoritative()});window.addEventListener('online',connect);
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

renderTask();applyLocale();connect();reloadAuthoritative();
