[platformio]
default_envs = cores3

[env:cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  m5stack/M5Unified
  links2004/WebSockets
  bblanchon/ArduinoJson
build_flags =
  -Wall
  -Wextra
  -Werror=return-type
